language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

install: mvn install -DskipTests=true -Dgpg.skip=true

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
